### ISSUE TITLE
Ajuste tirolesa

### ISSUE THREAD

**Issue by Jubabibou** [buff-buff-studio/Solis#294]
- tentar entender o porquê da tirolesa as vezes ficar bugada quando vista do lado de fora - o personagem parece que acompanha a tirolesa com certo delay. Se for uma questão de network, discutir com o Árnilsen como isso pode ser resolvido
- Colocar um fio entre elas

**Comment by SergioMacellani** [comment]
@giomelo acrescentando a fala da julia, quando você ta na tirolesa também fica estranho a movimentação, não é só quem está do lado de fora
